#!/bin/bash
set -o errexit
export REACT_APP_CHATGPT_CLONE_FRONTEND_URL=$CHATGPT_CLONE_FRONTEND_URL
export REACT_APP_CHATGPT_CLONE_BACKEND_URL=$CHATGPT_CLONE_BACKEND_URL
export REACT_APP_MONGODB_URI=$MONGODB_URI
export REACT_APP_MONGODB_DBNAME=$MONGODB_DBNAME
npm install && npm run build